export const ORDER_ALL_REQUEST="ORDER_ALL_REQUEST";
export const ORDER_ALL_SUCCESS="ORDER_ALL_SUCCESS";
export const ORDER_ALL_FAIL="ORDER_ALL_FAIL";
export const ORDER_ALL_RESET="ORDER_ALL_RESET";

export const ORDER_DETAILS_FAIL="ORDER_DETAILS_FAIL";
export const ORDER_DETAILS_REQUEST="ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS="ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_RESET="ORDER_DETAILS_RESET";

export const ORDER_DELIVERED_REQUEST="ORDER_DELIVERED_REQUEST";
export const ORDER_DELIVERED_SUCCESS="ORDER_DELIVERED_SUCCESS";
export const ORDER_DELIVERED_FAIL="ORDER_DELIVERED_FAIL";
